<?php
require_once "Database.php";

class Store extends Database
{

  public function createAccount($username, $password)
  {
    $sql = "INSERT INTO accounts(username, password) VALUES('$username', '$password')";

    $result = $this->conn->query($sql);
    //$this->conn->query($sql) ~~ will execute the SQL statement;

    if ($result == false) {
      die("CANNOT ADD ACCOUNTS: " . $this->conn->error);
    } else {
      return true;
    }
  }

  public function createUser($first_name, $last_name, $address, $email, $contact_number)
  {
    $user_account_id = $this->conn->insert_id;
    //$this-conn-insert_id ~~ get the last sued id generated by the last query.

    $sql = "INSERT INTO users(first_name, last_name, address,email, contact_number, account_id) VALUES ('$first_name', '$last_name', '$address', '$email','$contact_number', '$user_account_id')";

    if ($this->conn->query($sql)) {
      header("Location:login.php");
    } else {
      die("CANNOT ADD USER: " . $this->conn->error);
    }
  }
  public function login($username, $password)
  {
    $sql = "SELECT * FROM accounts INNER JOIN users ON users.account_id = accounts.account_id WHERE accounts.username = '$username' AND accounts.password='$password' ";

    $result = $this->conn->query($sql);

    if ($result->num_rows == 1) {
      $row = $result->fetch_assoc();
      $_SESSION['user_id'] = $row['user_id'];
      $_SESSION['username'] = $row['username'];
      $_SESSION['first_name'] = $row['first_name'];
      $_SESSION['last_name'] = $row['last_name'];
      $_SESSION['status'] = $row['status'];

      header("Location:storeUI.php");
      
    } else {
      return "Invalid Credentials";
    }
  }
  public function display_users(){
    $sql = "SELECT * FROM users INNER JOIN accounts WHERE users.account_id = accounts.account_id";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      return false;
    }
}

public function delete_user($id){
  $sql = "DELETE  users,accounts FROM users  INNER JOIN accounts ON users.account_id = accounts.account_id WHERE users.account_id = $id";
  $result = $this->conn->query($sql);

  if($result == TRUE){
    header('location: profile.php');
  }else{
    die("ERROR: ".$this->conn->error);
  }
}
public function get_user_data($id){
   $sql = "SELECT * FROM users INNER JOIN accounts ON users.account_id = accounts.account_id WHERE users.account_id = '$id'";
   $result = $this->conn->query($sql);

   if($result == TRUE){
     return $result->fetch_assoc();
   }else{
     die('ERROR: '.$this->conn->error);
   }
}
public function update_user($first_name,$last_name,$address,$email,$contact_number,$id){
  $sql = "UPDATE users SET first_name = '$first_name',last_name = '$last_name',address = '$address',email = '$email', contact_number = '$contact_number' WHERE user_id ='$id'";

  $result = $this->conn->query($sql);
  if($result == TRUE){
    header('location: profile.php');
  }else{
      die('ERROR '.$this->conn->error);

  }
}

public function update_account($username,$password,$id){
  $sql = "UPDATE accounts SET username = '$username', password ='$password' WHERE account_id = '$id'";

  $result = $this->conn->query($sql);
  if($result == TRUE){
      return TRUE;
  }else{
      die('ERROR '.$this->conn->error);
  }
}


public function update_account_user($first_name,$last_name,$address,$email,$contact_number,$username,$password,$id){
  $sql = "UPDATE users,accounts INNER JOIN accounts ON users.account_id = accounts.account_id SET users.first_name = '$first_name',users.last_name = '$last_name',users.address = '$address',users.email = '$email',users.contact_number = '$contact_number',accounts.username = '$username',accouns.password = '$password' WHERE users.user_id = '$id'";

  $result = $this->conn->query($sql);
  if($result == TRUE){
    header('location: profile.php');
  }else{
      die('ERROR '.$this->conn->error);

  }
}


  public function add_item($item_name,$Price,$description){
    $sql = "INSERT INTO products(product_name, price, description) VALUES('$item_name','$Price','$description')";

    if($this->conn->query($sql)){
      header("Location:adminUI.php");
    }else{
      die("CANNOT ADD USER: " . $this->conn->error);
    }
  }
  public function get_items(){
    $sql = "SELECT * FROM products";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      return false;
    }
  }
   public function add_to_cart($product_name,$product_price,$user_id){
     $sql = "INSERT INTO cart(product_name,product_price,user_id) VALUES ('$product_name','$product_price','$user_id')";

     if($this->conn->query($sql)){
      //header("Location:http://localhost/e-commerce/cart.php");
      echo "<div class = 'alert alert-success'>Added to cart Successfully</div>";
     }else{
       die("CANNOT ADD USER: " .$this->conn->error);
     }
   }
   public function see_cart($user_id){
    $sql = "SELECT * FROM cart WHERE user_id ='$user_id' AND status = 'cart'";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      die('ERROR '.$this->conn->error);
    }
   }
   
 
  public function confirmation($user_id){
     $sql = "INSERT INTO product_all(product_name,product_price,user_id) SELECT product_name,product_price,user_id FROM cart where user_id = '$user_id'";

     if($this->conn->query($sql)){
       $sql_delete = "DELETE FROM cart where user_id = '$user_id'";
       if($this->conn->query($sql_delete)){
        // header("Location:http://localhost/e-commerce/cart.php");
        // echo "<div class = 'alert alert-success'>Added to cart Successfully</div>";
        return true;
       }else{
        die("CANNOT ADD USER: " .$this->conn->error);
       }
     }else{
       die("CANNOT ADD USER: " .$this->conn->error);
     }
   }
   public function productall($user_id){
    $sql = "SELECT * FROM cart WHERE user_id ='$user_id'";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      return false;
    }
   }
   public function change_item_status($id){
      $sql = "UPDATE cart SET status='paid' WHERE item_id = '$id'";
      $result = $this->conn->query($sql);

      if($result == FALSE ){
        die("ERROR: ". $this->conn->error);

      }

   }
   public function see_paid($user_id){
    $sql = "SELECT * FROM cart WHERE user_id ='$user_id' AND status = 'paid'";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      die('ERROR '.$this->conn->error);
    }
   }
  
  }

